version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    labels:
      - "dependencies"
      - "actions"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "quarterly"
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "python"
    groups:
      python:
        patterns:
          - "*"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "quarterly"
    labels:
      - "dependencies"
      - "pre-commit"
    groups:
      pre-commit:
        patterns:
          - "*"
