deskew: true
voxel_size: 1.0
max_points_per_voxel: 20
max_range: 100.0
min_range: 1.0
convergence_criterion: 0.00001
max_correspondance_distance: 0.5
max_num_threads: 0
initialization_phase: false
max_expected_jerk: 3.0
min_beta: 200
double_downsample: true
# provide extrinsics if you're not using a rosbag or it doesn't have a tf tree
# extrinsic_imu2base_quat_xyzw_xyz: []
# extrinsic_lidar2base_quat_xyzw_xyz: []
