name: Core C++ Tests Ubuntu 24.04 ARM
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  core_tests_ubuntu_2404_arm:
    uses: ./.github/workflows/core_tests_reusable.yaml
    with:
      run_os: ubuntu-24.04-arm
