name: Python Bindings
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  python_bindings:
    name: Build python and run pytest on ${{ matrix.os }}
    env:
      GIT_LFS_SKIP_SMUDGE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # targetting the older versions here, and the newer versions for the pypi workflow
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14, windows-2022]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python3
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Build with pip
        run: |
          python -m pip install --verbose ./python/ pytest
      - name: Run pytest
        run: |
          pytest python/
