# TODO: need to use a matrix to check all the different ros versions we'll support later
name: ROS Jazzy Build
on:
  push:
    branches: ["workflows"]
  pull_request:
    branches: ["workflows"]
jobs:
  ros_jazzy_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Run colcon build in ROS Jazzy Docker container
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace osrf/ros:jazzy-desktop bash -c "
            apt-get update && apt-get install -y ninja-build build-essential cmake &&
            source /opt/ros/jazzy/setup.bash &&
            colcon build --event-handlers console_direct+"
