name: ROS Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  ros_build:
    name: ROS build for ${{ matrix.ros_distro }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [humble, jazzy, kilted]
        # no rolling build for now, because i'm sure thats gonna break often
    container:
      image: ${{ (matrix.ros_distro == 'humble' && 'alexsilener/ros_humble_desktop_cmake_328_ninja') || (matrix.ros_distro == 'jazzy' && 'osrf/ros:jazzy-desktop') || (matrix.ros_distro == 'kilted' && 'osrf/ros:kilted-desktop') }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y ninja-build build-essential cmake
      - name: Source ROS environment and build
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          colcon build --event-handlers console_direct+
