# We dont do a rolling build for now, because i'm sure thats gonna break often
name: ROS Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  ros_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [jazzy, kilted]
        # ros_distro: [humble, jazzy, kilted]
    container:
      image: osrf/ros:${{ matrix.ros_distro }}-desktop
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y ninja-build build-essential cmake
      - name: Source ROS environment and build
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          colcon build --event-handlers console_direct+
